// js/plan.js
// Esta constante contiene la información estructurada de cada día del plan.
// **ATENCIÓN: Se asume que este archivo se carga antes que app.js**

const PLAN_DIARIO = [
    { day: 1, word: 'Hallo', wordTrans: 'Hola', plural: 'Hallo', title: 'Saludos y Presentaciones', journalPrompt: 'Escribe 3 frases presentándote.', exampleSentence: 'Hallo, wie geht es Ihnen?', exampleTranslation: 'Hola, ¿cómo está usted?', learningGoals: ["Saludar y despedirse formal e informalmente.", "Presentarse (nombre).", "Preguntar '¿Cómo estás?' y responder."], lessonContent: `
        <h3>Saludos Básicos (Grüße)</h3>
        <p>La forma más común y versátil de saludar es <strong>Hallo</strong> (Hola). Para ser más específico con el tiempo del día:</p>
        <ul>
            <li><strong>Guten Morgen!</strong> (Buenos días - hasta el mediodía)</li>
            <li><strong>Guten Tag!</strong> (Buen día - de mediodía a tarde, el más neutral)</li>
            <li><strong>Guten Abend!</strong> (Buenas tardes/noches - a partir de las 6 PM)</li>
        </ul>
        <h3>Presentaciones y Formas de Cortesía</h3>
        <p>En alemán, la cortesía es clave. Usamos <strong>Sie</strong> (Usted, formal) y <strong>du</strong> (tú, informal).</p>
        <p>Para preguntar el nombre:</p>
        <ul>
            <li>Formal: <strong>Wie heißen Sie?</strong> (¿Cómo se llama Usted?)</li>
            <li>Informal: <strong>Wie heißt du?</strong> (¿Cómo te llamas tú?)</li>
        </ul>
        <p>Para responder: <strong>Ich heiße [Tu Nombre].</strong> (Yo me llamo [Tu Nombre]).</p>
    `, tasks: [ { id:'d1-t1', icon:'🧠', color:'bg-pink-50', desc:'Vocabulario: Aprende 5 saludos y 3 despedidas.', time:'20 min' }, { id:'d1-t2', icon:'🎧', color:'bg-purple-50', desc:'Escucha un diálogo "Hallo, wie geht\'s?" y repite.', time:'15 min' }, { id:'d1-t3', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 3 mini-diálogos presentándote.', time:'15 min' } ] },
    
    { day: 2, word: 'die Woche', wordTrans: 'la semana', plural: 'die Wochen', title: 'Formal (Sie) vs. Informal (du)', journalPrompt: 'Escribe 2 frases formales y 2 informales.', exampleSentence: 'Diese Woche habe ich viel Arbeit.', exampleTranslation: 'Esta semana tengo mucho trabajo.', learningGoals: ["Diferenciar entre tratamiento formal (Sie) e informal (du).", "Usar las formas correctas al preguntar el nombre."], lessonContent: `
        <h3>El Dilema Sie vs. Du</h3>
        <p>La elección entre <strong>Sie (Usted)</strong> y <strong>du (tú)</strong> es crucial en Alemania. El error más común de los principiantes es usar "du" con desconocidos o personas mayores.</p>
        <ul>
            <li><strong>Sie:</strong> Se usa con desconocidos, clientes, jefes, profesores y personas mayores (salvo que ellos te ofrezcan usar "du"). Siempre va con mayúscula inicial.</li>
            <li><strong>du:</strong> Se usa con amigos, familia, niños y adolescentes, o si te lo han ofrecido explícitamente ("Wir können uns duzen" / "Podemos tutearnos").</li>
        </ul>
        <h3>La Palabra del Día: die Woche</h3>
        <p>La palabra <strong>die Woche</strong> (la semana) es femenina, por lo que usa el artículo femenino <strong>die</strong>. Su plural es <strong>die Wochen</strong>.</p>
        <p>Aprender la palabra con el artículo es vital: <strong>die Woche, die Wochen</strong>.</p>
    `, tasks: [ { id:'d2-t1', icon:'🧠', color:'bg-pink-50', desc:'Gramática: Entiende la diferencia entre "Sie" (formal) y "du" (informal).', time:'15 min' }, { id:'d2-t2', icon:'📖', color:'bg-yellow-50', desc:'Lee ejemplos de "Wie heißen Sie?" vs. "Wie heißt du?".', time:'15 min' }, { id:'d2-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica presentarte de ambas formas en voz alta.', time:'15 min' } ] },
    
    { day: 3, word: 'sein', wordTrans: 'ser/estar', title: 'El Verbo "sein" (Ser/Estar)', journalPrompt: 'Escribe una frase con cada conjugación de "sein".', exampleSentence: 'Ich bin müde.', exampleTranslation: 'Estoy cansado/a.', learningGoals: ["Conjugar el verbo 'sein' (ser/estar) en presente.", "Formar frases básicas usando 'sein' (nacionalidad, profesión, estado)."], lessonContent: `
        <h3>El Verbo Irregular más Importante: sein</h3>
        <p><strong>Sein</strong> (ser/estar) es irregular y fundamental. Debes memorizar estas conjugaciones, ya que se usa constantemente para indicar identidad, estado y ubicación.</p>
        <div class="p-3 bg-red-50 rounded-md font-mono text-sm">
            <p>Ich <strong>bin</strong> (Yo soy/estoy)</p>
            <p>Du <strong>bist</strong> (Tú eres/estás)</p>
            <p>Er/Sie/Es <strong>ist</strong> (Él/Ella/Ello es/está)</p>
            <p>Wir <strong>sind</strong> (Nosotros somos/estamos)</p>
            <p>Ihr <strong>seid</strong> (Vosotros sois/estáis)</p>
            <p>Sie/sie <strong>sind</strong> (Usted/Ellos son/están)</p>
        </div>
        <h3>Ejemplos de Uso</h3>
        <ul>
            <li>Nacionalidad: "Ich <strong>bin</strong> Spanier."</li>
            <li>Estado: "Er <strong>ist</strong> glücklich."</li>
            <li>Profesión: "Wir <strong>sind</strong> Studenten."</li>
        </ul>
    `, tasks: [ { id:'d3-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Conjuga "sein" (ich bin, du bist, er/sie/es ist...).', time:'20 min' }, { id:'d3-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases usando "sein" (Ej: Ich bin müde, Du bist nett).', time:'20 min' }, { id:'d3-t3', icon:'🗣️', color:'bg-orange-50', desc:'Di las conjugaciones de "sein" en voz alta 10 veces.', time:'10 min' } ] },
    
    { day: 4, word: 'haben', wordTrans: 'tener', title: 'El Verbo "haben" (Tener)', journalPrompt: 'Escribe 5 cosas que tienes.', exampleSentence: 'Wir haben Hunger.', exampleTranslation: 'Tenemos hambre.', learningGoals: ["Conjugar el verbo 'haben' (tener) en presente.", "Formar frases básicas usando 'haben' (posesión, edad, sensaciones)."], lessonContent: `
        <h3>Conjugando el Verbo: haben</h3>
        <p><strong>Haben</strong> (tener) también es irregular, pero se usa para posesión y algunas expresiones de estado (como tener hambre o sed).</p>
        <div class="p-3 bg-red-50 rounded-md font-mono text-sm">
            <p>Ich <strong>habe</strong> (Yo tengo)</p>
            <p>Du <strong>hast</strong> (Tú tienes)</p>
            <p>Er/Sie/Es <strong>hat</strong> (Él/Ella/Ello tiene)</p>
            <p>Wir <strong>haben</strong> (Nosotros tenemos)</p>
            <p>Ihr <strong>habt</strong> (Vosotros tenéis)</p>
            <p>Sie/sie <strong>haben</strong> (Usted/Ellos tienen)</p>
        </div>
        <h3>Importante: haben vs. sein</h3>
        <p>En alemán, las sensaciones (hambre, sed, sueño) se expresan con <strong>haben</strong> (tener), no con <strong>sein</strong> (estar), a diferencia del español.</p>
        <ul>
            <li>Tener hambre: Ich <strong>habe</strong> Hunger.</li>
            <li>Tener 30 años: Er <strong>hat</strong> dreißig Jahre.</li>
        </ul>
    `, tasks: [ { id:'d4-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Conjuga "haben" (ich habe, du hast, er/sie/es hat...).', time:'20 min' }, { id:'d4-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases con "haben" (Ej: Ich habe einen Hund, Du hast Hunger).', time:'20 min' }, { id:'d4-t3', icon:'🎧', color:'bg-pink-50', desc:'Escucha un audio que use "sein" y "haben".', time:'15 min' } ] },
    
    { day: 5, word: 'Woher?', wordTrans: '¿De dónde?', title: 'Preguntas (W-Fragen)', journalPrompt: 'Escribe 3 preguntas W y sus respuestas.', exampleSentence: 'Woher kommen Sie?', exampleTranslation: '¿De dónde viene usted?', learningGoals: ["Identificar y usar las principales partículas interrogativas (Wer, Was, Wo, Wie, Wann, Woher, etc.).", "Formular preguntas básicas sobre información personal."], lessonContent: `
        <h3>Las Partículas Interrogativas (W-Fragen)</h3>
        <p>Las preguntas que no se responden con sí/no (como las de información personal) comienzan con una 'W'.</p>
        <ul>
            <li><strong>Wer?</strong> (¿Quién?) Ejemplo: Wer ist das?</li>
            <li><strong>Was?</strong> (¿Qué?) Ejemplo: Was machen Sie?</li>
            <li><strong>Wo?</strong> (¿Dónde?) Ejemplo: Wo wohnst du?</li>
            <li><strong>Woher?</strong> (¿De dónde?) Ejemplo: Woher kommen Sie?</li>
            <li><strong>Wie?</strong> (¿Cómo?) Ejemplo: Wie geht es dir?</li>
        </ul>
        <h3>Estructura Clave</h3>
        <p>La regla de oro en alemán es que el verbo (la acción) siempre debe ir en la <strong>segunda posición</strong> de la oración, incluso en las preguntas con W-Fragen:</p>
        <p><strong>[W-Frage] + [Verbo conjugado] + [Sujeto/Complementos]</strong></p>
        <p>Ejemplo: <strong>Wie</strong> <strong>heißen</strong> Sie? / <strong>Wo</strong> <strong>ist</strong> die Toilette?</p>
    `, tasks: [ { id:'d5-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende las "W-Fragen" (Wer, Was, Wo, Wie, Wann, Woher).', time:'20 min' }, { id:'d5-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe una pregunta con cada "W-Frage" (Ej: Wer bist du? Wo wohnst du?).', time:'20 min' }, { id:'d5-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica preguntar y responder estas preguntas básicas en voz alta.', time:'15 min' } ] },
    
    { day: 6, word: 'die Zahl', wordTrans: 'el Número', plural: 'die Zahlen', title: 'El Alfabeto y Números (0-20)', journalPrompt: 'Escribe tu edad y número de teléfono.', exampleSentence: 'Meine Lieblingszahl ist sieben.', exampleTranslation: 'Mi número favorito es el siete.', learningGoals: ["Reconocer y pronunciar el alfabeto alemán.", "Contar del 0 al 20."], lessonContent: `
        <h3>El Alfabeto Alemán (Das Alphabet)</h3>
        <p>El alfabeto es similar al español, pero tiene letras con diéresis (Ä, Ö, Ü) y la eszett (ß).</p>
        <p><strong>Puntos clave:</strong></p>
        <ul>
            <li>La letra V se pronuncia como "F" (Ej: Vater -> Fater).</li>
            <li>La letra W se pronuncia como "V" (Ej: Woche -> Voche).</li>
            <li>La letra Z se pronuncia como "Ts" (Ej: Zahl -> Tsal).</li>
        </ul>
        <h3>Números 0-20</h3>
        <p>Es esencial memorizar los números hasta el 12. A partir del 13, se forma como en inglés: [Unidad] + [diez].</p>
        <ul>
            <li><strong>11:</strong> elf, <strong>12:</strong> zwölf</li>
            <li><strong>13:</strong> dreizehn, <strong>16:</strong> sechzehn (¡Ojo! Pierde la 's')</li>
        </ul>
    `, tasks: [ { id:'d6-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende los números de 0 a 20.', time:'20 min' }, { id:'d6-t2', icon:'🎧', color:'bg-pink-50', desc:'Escucha una canción del alfabeto alemán y cántala.', time:'15 min' }, { id:'d6-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica decir tu número de teléfono y edad.', time:'15 min' } ] },
    
    { day: 7, word: 'Repaso', wordTrans: 'Revisión', title: 'Repaso Semana 1', journalPrompt: 'Escribe un párrafo presentándote.', exampleSentence: 'Heute machen wir einen Repaso.', exampleTranslation: 'Hoy hacemos un repaso.', learningGoals: ["Consolidar saludos, presentaciones.", "Repasar conjugaciones de 'sein' y 'haben'.", "Practicar W-Fragen y números básicos."], lessonContent: `<p>Esta semana se centró en las bases de la comunicación: presentarse, preguntar y responder información personal, y los dos verbos más importantes: <strong>sein</strong> (ser/estar) y <strong>haben</strong> (tener).</p><h3>Autoevaluación Rápida</h3><p>Intenta conjugar 'sein' y 'haben' para 'Ich', 'Du', 'Er/Sie/Es' de memoria. Si lo logras, estás listo para la siguiente semana.</p>`, tasks: [ { id:'d7-t1', icon:'📖', color:'bg-yellow-50', desc:'Lee un diálogo corto (A1) e identifica saludos, "sein", "haben".', time:'20 min' }, { id:'d7-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe un párrafo corto (3-5 frases) presentándote.', time:'20 min' }, { id:'d7-t3', icon:'🧠', color:'bg-purple-50', desc:'Repasa vocabulario días 1-6 con flashcards.', time:'15 min' } ] },
    // --- RESTO DE DÍAS (Sin contenido de lección detallado, solo placeholders) ---
    // DEBES añadir el contenido de la lección para cada día (lessonContent)
    { day: 8, word: 'die Familie', wordTrans: 'la Familia', plural: 'die Familien', title: 'La Familia', journalPrompt: 'Describe a tu familia.', exampleSentence: 'Meine Familie wohnt in Spanien.', exampleTranslation: 'Mi familia vive en España.', learningGoals: ["Nombrar a los miembros básicos de la familia.", "Describir relaciones familiares simples."], lessonContent: `<h3>¡Bienvenido al día 8!</h3><p>Aquí aprenderás el vocabulario de la familia. Recuerda siempre aprender el sustantivo junto a su artículo (der/die/das).</p>`, tasks: [ { id:'d8-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende los miembros de la familia.', time:'20 min' }, { id:'d8-t2', icon:'✍️', color:'bg-yellow-50', desc:'Dibuja tu árbol genealógico y etiqueta en alemán.', time:'20 min' }, { id:'d8-t3', icon:'🗣️', color:'bg-orange-50', desc:'Describe a tu familia en frases simples.', time:'15 min' } ] },
    { day: 9, word: 'der', wordTrans: 'el (masc.)', title: 'Artículos: Nominativo', journalPrompt: 'Escribe 10 sustantivos con su artículo.', exampleSentence: 'Der Stuhl ist alt.', exampleTranslation: 'La silla es vieja.', learningGoals: ["Identificar los 3 géneros gramaticales.", "Usar los artículos definidos (der, die, das) en nominativo."], lessonContent: `<h3>Gramática del día: El Nominativo y los Artículos</h3><p>El nominativo es el caso del sujeto de la oración. ¡Recuerda que todos los sustantivos alemanes llevan mayúscula inicial!</p><p>Masculino: <strong>Der</strong> Mann | Femenino: <strong>Die</strong> Frau | Neutro: <strong>Das</strong> Kind</p>`, tasks: [ { id:'d9-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende los 3 géneros y artículos.', time:'20 min' }, { id:'d9-t2', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 sustantivos CON su artículo.', time:'15 min' }, { id:'d9-t3', icon:'✍️', color:'bg-yellow-50', desc:'Haz una lista de 5 objetos y busca su género/artículo.', time:'20 min' } ] },
    { day: 10, word: 'den', wordTrans: 'el (masc. acus.)', title: 'Artículos: Akkusativ', journalPrompt: 'Escribe 5 frases en Acusativo.', exampleSentence: 'Ich sehe den Mann.', exampleTranslation: 'Veo al hombre.', learningGoals: ["Comprender el caso acusativo.", "Aplicar el cambio der -> den."], lessonContent: `<h3>El Acusativo (Objeto Directo)</h3><p>El acusativo se usa para el objeto directo de la acción. Solo el artículo masculino cambia: <strong>der</strong> se convierte en <strong>den</strong>.</p><p>Ejemplo: Ich habe <strong>einen</strong> Hund (masc. indefinito) | Ich sehe <strong>den</strong> Tisch (masc. definido).</p>`, tasks: [ { id:'d10-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Entiende el Akkusativ (objeto directo). "der" -> "den".', time:'20 min' }, { id:'d10-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases con "haben" + objeto directo.', time:'20 min' }, { id:'d10-t3', icon:'📖', color:'bg-yellow-50', desc:'Completa 10 ejercicios online de Nom vs Akk.', time:'15 min' } ] },
    { day: 11, word: 'ein', wordTrans: 'un', title: 'Artículos Indefinidos', journalPrompt: 'Escribe 3 frases Nom. y 3 Akk.', exampleSentence: 'Das ist ein Tisch.', exampleTranslation: 'Esto es una mesa.', learningGoals: ["Usar artículos indefinidos Nom/Akk.", "Reconocer los cambios en el acusativo."], lessonContent: `<h3>Artículos Indefinidos: ein/eine</h3><p>En Nominativo son: ein (masc.), eine (fem.), ein (neutro). En Acusativo: **einen** (masc.), eine (fem.), ein (neutro).</p>`, tasks: [ { id:'d11-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende \'ein\' (Nom) y \'einen\' (Akk).', time:'20 min' }, { id:'d11-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe frases: "Das ist ein..." vs. "Ich habe einen...".', time:'20 min' }, { id:'d11-t3', icon:'🗣️', color:'bg-orange-50', desc:'Señala objetos y di "Das ist ein/eine...".', time:'10 min' } ] },
    { day: 12, word: 'mein', wordTrans: 'mi', title: 'Posesivos (mein, dein)', journalPrompt: 'Escribe 5 frases con posesivos.', exampleSentence: 'Mein Bruder heißt Peter.', exampleTranslation: 'Mi hermano se llama Peter.', learningGoals: ["Usar posesivos 'mein' y 'dein'.", "Declinar posesivos."], lessonContent: `<h3>Posesivos: mein y dein</h3><p>Los posesivos se declinan como los artículos indefinidos. Si el sustantivo es femenino o plural, añaden '-e': mein/meine, dein/deine.</p>`, tasks: [ { id:'d12-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende "mein/meine" y "dein/deine" en Nominativo.', time:'20 min' }, { id:'d12-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases sobre tu familia y cosas.', time:'20 min' }, { id:'d12-t3', icon:'🗣️', color:'bg-orange-50', desc:'Describe a tu familia usando posesivos.', time:'15 min' } ] },
    { day: 13, word: 'rot', wordTrans: 'rojo', title: 'Colores y Adjetivos Básicos', journalPrompt: 'Describe 5 objetos.', exampleSentence: 'Das Auto ist rot.', exampleTranslation: 'El coche es rojo.', learningGoals: ["Nombrar colores.", "Usar adjetivos básicos."], lessonContent: `<h3>Describiendo el mundo: Colores</h3><p>Los colores se usan como en español, pero van sin declinación cuando actúan como predicado (después del verbo sein): Das Auto ist <strong>rot</strong>.</p>`, tasks: [ { id:'d1Next-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 colores y 5 adjetivos.', time:'20 min' }, { id:'d13-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases describiendo objetos.', time:'20 min' }, { id:'d13-t3', icon:'🎧', color:'bg-pink-50', desc:'Escucha "Nicos Weg" (A1) e identifica adjetivos.', time:'15 min' } ] },
    { day: 14, word: 'das Zimmer', wordTrans: 'la Habitación', plural: 'die Zimmer', title: 'Repaso Semana 2', journalPrompt: 'Describe tu habitación.', exampleSentence: 'Mein Zimmer ist klein.', exampleTranslation: 'Mi habitación es pequeña.', learningGoals: ["Consolidar artículos Nom/Akk.", "Practicar vocabulario y posesivos."], lessonContent: `<h3>Repaso de Artículos y Casos</h3><p>Este día es para asegurar que las declinaciones de los artículos definidos e indefinidos en Nominativo y Acusativo son claras. Céntrate en identificar el objeto directo.</p>`, tasks: [ { id:'d14-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Haz un mapa mental de Nom vs Akk.', time:'15 min' }, { id:'d14-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe un párrafo describiendo tu habitación.', time:'25 min' }, { id:'d14-t3', icon:'📖', color:'bg-yellow-50', desc:'Lee un texto A1 sobre una familia.', time:'15 min' } ] },
    { day: 15, word: 'lernen', wordTrans: 'aprender', title: 'Verbos Regulares', journalPrompt: 'Conjuga "lernen".', exampleSentence: 'Ich lerne Deutsch.', exampleTranslation: 'Aprendo alemán.', learningGoals: ["Conjugar verbos regulares.", "Usar la terminación correcta según el pronombre."], lessonContent: `<h3>La Regla de la Terminación -en</h3><p>La mayoría de verbos terminan en -en. Para conjugar, quita '-en' y añade las terminaciones: -e, -st, -t, -en, -t, -en.</p>`, tasks: [ { id:'d15-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende la conjugación regular.', time:'20 min' }, { id:'d15-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases con verbos regulares (Ej: Ich lerne).', time:'20 min' }, { id:'d15-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica la conjugación de 3 verbos comunes.', time:'15 min' } ] },
    { day: 16, word: 'sprechen', wordTrans: 'hablar', title: 'Verbos Irregulares (con cambio)', journalPrompt: 'Conjuga "sprechen".', exampleSentence: 'Ich spreche Spanisch.', exampleTranslation: 'Hablo español.', learningGoals: ["Identificar verbos irregulares con cambio de vocal (e->i).", "Conjugar 'sprechen' y 'essen'."], lessonContent: `<h3>Verbos con cambio de Vocal</h3><p>Algunos verbos como 'sprechen' cambian la vocal de la raíz en la 2ª y 3ª persona del singular: du sprichst, er/sie/es spricht.</p>`, tasks: [ { id:'d16-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende la conjugación de \'sprechen\' y \'essen\'.', time:'20 min' }, { id:'d16-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 4 frases con estos verbos.', time:'20 min' }, { id:'d16-t3', icon:'📖', color:'bg-yellow-50', desc:'Busca 3 verbos más con cambio e->i.', time:'15 min' } ] },
    { day: 17, word: 'können', wordTrans: 'poder', title: 'Verbos Modales (Parte 1)', journalPrompt: 'Escribe 3 cosas que puedes hacer.', exampleSentence: 'Ich kann gut singen.', exampleTranslation: 'Puedo cantar bien.', learningGoals: ["Conjugar el modal 'können' (poder).", "Usar la estructura modal: Modal en pos. 2 + Infinitivo al final."], lessonContent: `<h3>Verbos Modales (Modalverben)</h3><p>Los modales son irregulares en el singular y envían el verbo principal al final de la oración en infinitivo: Ich kann Deutsch <strong>sprechen</strong>.</p>`, tasks: [ { id:'d17-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Conjuga \'können\' (poder).', time:'20 min' }, { id:'d17-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases con \'können\'.', time:'20 min' }, { id:'d17-t3', icon:'🗣️', color:'bg-orange-50', desc:'Pregunta a alguien (imaginario) "¿Puedes...?" 5 veces.', time:'15 min' } ] },
    { day: 18, word: 'müssen', wordTrans: 'deber (oblig.)', title: 'Verbos Modales (Parte 2)', journalPrompt: 'Escribe 3 cosas que debes hacer.', exampleSentence: 'Ich muss arbeiten.', exampleTranslation: 'Debo trabajar.', learningGoals: ["Conjugar 'müssen' (obligación) y 'dürfen' (permiso).", "Practicar la estructura modal."], lessonContent: `<h3>Verbos Modales: müssen y dürfen</h3><p><strong>müssen</strong>: Necesidad fuerte o obligación (Ich muss lernen = Debo estudiar).</p><p><strong>dürfen</strong>: Permiso (Hier dürfen Sie nicht rauchen = Aquí no está permitido fumar).</p>`, tasks: [ { id:'d18-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Conjuga \'müssen\' y \'dürfen\'.', time:'20 min' }, { id:'d18-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases con \'müssen\' y \'dürfen\'.', time:'20 min' }, { id:'d18-t3', icon:'📖', color:'bg-yellow-50', desc:'Identifica modales en un texto A1.', time:'15 min' } ] },
    { day: 19, word: 'die Uhr', wordTrans: 'el reloj', plural: 'die Uhren', title: 'La Hora (Formal e Informal)', journalPrompt: 'Escribe tu horario del día.', exampleSentence: 'Es ist vierzehn Uhr.', exampleTranslation: 'Son las catorce (dos de la tarde).', learningGoals: ["Decir la hora de forma formal (oficial).", "Decir la hora de forma informal."], lessonContent: `<h3>Cómo decir la hora</h3><p>Formal: Se usa el formato de 24 horas (Es ist vierzehn Uhr).</p><p>Informal: Se usan palabras como 'halb' (y media), 'viertel' (y cuarto/menos cuarto). ¡Ojo! 'halb' significa 'media hora antes de la siguiente': halb drei = 2:30.</p>`, tasks: [ { id:'d19-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende los números de 0 a 60.', time:'20 min' }, { id:'d19-t2', icon:'✍️', color:'bg-yellow-50', desc:'Practica decir 10 horas distintas (formal/informal).', time:'20 min' }, { id:'d19-t3', icon:'🎧', color:'bg-pink-50', desc:'Escucha y repite diálogos sobre pedir la hora.', time:'15 min' } ] },
    { day: 20, word: 'das Hobby', wordTrans: 'el Hobby', plural: 'die Hobbys', title: 'Actividades y Hobbies', journalPrompt: 'Escribe 5 hobbies que tienes.', exampleSentence: 'Mein Hobby ist Lesen.', exampleTranslation: 'Mi hobby es leer.', learningGoals: ["Nombrar actividades de tiempo libre y hobbies.", "Preguntar sobre hobbies."], lessonContent: `<h3>¿Qué te gusta hacer?</h3><p>La forma más sencilla de preguntar es: Was machen Sie/machst du gern in der Freizeit?</p><p>Respuesta: Ich lese gern (Me gusta leer).</p>`, tasks: [ { id:'d20-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 hobbies y verbos de actividad.', time:'20 min' }, { id:'d20-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases sobre lo que haces en tu tiempo libre.', time:'20 min' }, { id:'d20-t3', icon:'🗣️', color:'bg-orange-50', desc:'Describe tu día (con horas y actividades).', time:'15 min' } ] },
    { day: 21, word: 'Repaso', wordTrans: 'Revisión', title: 'Repaso Semana 3', journalPrompt: 'Escribe una carta a un amigo invitándolo a una actividad.', exampleSentence: 'Wir wiederholen die Verben.', exampleTranslation: 'Repasamos los verbos.', learningGoals: ["Consolidar verbos regulares/irregulares y modales.", "Repasar la hora."], lessonContent: `<h3>Enfoque en Verbos y Estructura</h3><p>Asegúrate de que la posición del verbo y la conjugación de los modales y verbos irregulares son automáticas.</p>`, tasks: [ { id:'d21-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Conjuga todos los verbos aprendidos de memoria.', time:'20 min' }, { id:'d21-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe una carta corta (A1) a un amigo.', time:'25 min' }, { id:'d21-t3', icon:'📖', color:'bg-yellow-50', desc:'Revisa ejercicios de modales y la hora.', time:'15 min' } ] },
    { day: 22, word: 'der Bahnhof', wordTrans: 'la estación de tren', plural: 'die Bahnhöfe', title: 'Preposiciones Locales (Wo?)', journalPrompt: 'Escribe 5 frases con preposiciones.', exampleSentence: 'Der Bahnhof ist in der Nähe.', exampleTranslation: 'La estación de tren está cerca.', learningGoals: ["Usar preposiciones que rigen Dativo (Wo?).", "Preguntar y responder por ubicación."], lessonContent: `<h3>Preposiciones Fijas (Dativo)</h3><p>Las preposiciones como in, an, auf, unter, hinter, neben, über, vor, zwischen pueden regir Dativo cuando indican una posición fija (¿Dónde está? = Wo?).</p>`, tasks: [ { id:'d22-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 5 preposiciones de lugar (in, auf, unter, neben, vor).', time:'20 min' }, { id:'d22-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases de ubicación usando Dativo (Der Tisch ist auf **dem** Stuhl).', time:'20 min' }, { id:'d22-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica describir un mapa.', time:'15 min' } ] },
    { day: 23, word: 'in die Stadt', wordTrans: 'a la ciudad', title: 'Preposiciones Locales (Wohin?)', journalPrompt: 'Escribe 3 frases de movimiento.', exampleSentence: 'Ich gehe in die Stadt.', exampleTranslation: 'Voy a la ciudad.', learningGoals: ["Usar preposiciones que rigen Acusativo (Wohin?).", "Preguntar y responder por movimiento/destino."], lessonContent: `<h3>Preposiciones de Movimiento (Acusativo)</h3><p>Las mismas preposiciones (in, an, auf...) rigen Acusativo cuando indican una dirección o movimiento (¿Hacia dónde vas? = Wohin?).</p>`, tasks: [ { id:'d23-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende el cambio de Acusativo en preposiciones (Wo vs Wohin).', time:'20 min' }, { id:'d23-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases de movimiento (Ej: Ich gehe in **den** Park).', time:'20 min' }, { id:'d23-t3', icon:'📖', color:'bg-yellow-50', desc:'Lee textos de orientación en la ciudad.', time:'15 min' } ] },
    { day: 24, word: 'der Kaffee', wordTrans: 'el café', title: 'Comida y Bebida', journalPrompt: 'Escribe tu pedido ideal en un café.', exampleSentence: 'Ich trinke einen Kaffee.', exampleTranslation: 'Bebo un café.', learningGoals: ["Nombrar comidas y bebidas básicas.", "Hacer pedidos en restaurantes/cafés."], lessonContent: `<h3>¡A la mesa! (Am Tisch)</h3><p>Vocabulario esencial: der Kaffee, das Brot, die Butter, die Milch, das Wasser.</p><p>Para pedir: Ich möchte... / Ich hätte gern... (Quisiera... / Me gustaría...)</p>`, tasks: [ { id:'d24-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 palabras de comida y 5 de bebida.', time:'20 min' }, { id:'d24-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases sobre lo que comes/bebes.', time:'20 min' }, { id:'d24-t3', icon:'🗣️', color:'bg-orange-50', desc:'Simula un diálogo en un café.', time:'15 min' } ] },
    { day: 25, word: 'die Kleidung', wordTrans: 'la ropa', plural: 'die Kleidungen', title: 'Ropa y Precios', journalPrompt: 'Describe tu atuendo favorito.', exampleSentence: 'Die Kleidung ist schön.', exampleTranslation: 'La ropa es bonita.', learningGoals: ["Nombrar prendas de vestir básicas.", "Preguntar y decir precios.", "Usar números del 21 al 100."], lessonContent: `<h3>De Compras (Einkaufen)</h3><p>Frases clave: Was kostet...? (¿Cuánto cuesta...?)</p><p>Números grandes: se lee la unidad, luego 'und' (y), luego la decena: einundzwanzig (21).</p>`, tasks: [ { id:'d25-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 prendas de vestir.', time:'20 min' }, { id:'d25-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases describiendo ropa.', time:'20 min' }, { id:'d25-t3', icon:'🧠', color:'bg-purple-50', desc:'Repasa y practica números hasta 100.', time:'15 min' } ] },
    { day: 26, word: 'die E-Mail', wordTrans: 'el correo electrónico', plural: 'die E-Mails', title: 'Escribir E-mails y Cartas', journalPrompt: 'Escribe un e-mail a un amigo invitándolo a cenar.', exampleSentence: 'Ich schreibe eine E-Mail.', exampleTranslation: 'Escribo un correo electrónico.', learningGoals: ["Escribir saludos y despedidas de e-mails/cartas.", "Estructura de una invitación simple."], lessonContent: `<h3>Comunicación Escrita (Schriftliche Kommunikation)</h3><p>Saludos: Liebe/Lieber [Nombre] (para amigos); Sehr geehrte Damen und Herren (formal).</p><p>Cierre: Mit freundlichen Grüßen (formal); Viele Grüße (informal).</p>`, tasks: [ { id:'d26-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Aprende los marcadores de una carta/e-mail.', time:'20 min' }, { id:'d26-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe un e-mail de 5 frases para invitar a alguien.', time:'20 min' }, { id:'d26-t3', icon:'📖', color:'bg-yellow-50', desc:'Lee y analiza 3 e-mails A1.', time:'15 min' } ] },
    { day: 27, word: 'das Wetter', wordTrans: 'el clima', title: 'El Clima y las Estaciones', journalPrompt: 'Describe el clima de hoy.', exampleSentence: 'Das Wetter ist kalt.', exampleTranslation: 'El clima es frío.', learningGoals: ["Nombrar estaciones y condiciones climáticas básicas.", "Describir el clima."], lessonContent: `<h3>Hablando del Clima (Das Wetter)</h3><p>Frases clave: Wie ist das Wetter heute? (¿Cómo está el clima hoy?)</p><p>Respuesta: Es ist sonnig/regnerisch/kalt/warm (Está soleado/lluvioso/frío/cálido).</p>`, tasks: [ { id:'d27-t1', icon:'🧠', color:'bg-purple-50', desc:'Vocabulario: Aprende 10 palabras de clima y las 4 estaciones.', time:'20 min' }, { id:'d27-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe 5 frases sobre el clima de tu región.', time:'20 min' }, { id:'d27-t3', icon:'🗣️', color:'bg-orange-50', desc:'Practica frases de clima en voz alta.', time:'15 min' } ] },
    { day: 28, word: 'Repaso', wordTrans: 'Revisión', title: 'Repaso Semana 4', journalPrompt: 'Escribe un diálogo de 10 líneas sobre ir de compras.', exampleSentence: 'Wir üben die Dialoge.', exampleTranslation: 'Practicamos los diálogos.', learningGoals: ["Consolidar preposiciones Nom/Akk.", "Repasar vocabulario de comida/ropa.", "Practicar diálogos de la vida diaria."], lessonContent: `<h3>Cierre de Contenido A1</h3><p>Esta semana se centró en la aplicación del idioma en situaciones cotidianas: localización, movimiento, compras y clima. ¡Repasa lo que te resultó más difícil!</p>`, tasks: [ { id:'d28-t1', icon:'🧠', color:'bg-purple-50', desc:'Gramática: Repaso rápido de las reglas de Dativo vs Acusativo.', time:'20 min' }, { id:'d28-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe el diálogo de compras.', time:'25 min' }, { id:'d28-t3', icon:'📖', color:'bg-yellow-50', desc:'Lee los textos de las 4 semanas.', time:'15 min' } ] },
    { day: 29, word: 'alles', wordTrans: 'todo', title: 'Simulación de Examen (A1)', journalPrompt: 'Escribe 3 frases de las partes que fallaste.', exampleSentence: 'Ich habe fast alles verstanden.', exampleTranslation: 'Casi lo he entendido todo.', learningGoals: ["Medir el nivel A1 en comprensión lectora, auditiva y oral."], lessonContent: `<h3>Prepárate para el Examen</h3><p>Hoy es un día de simulación. Intenta hacer un examen modelo A1 online para identificar tus puntos débiles.</p>`, tasks: [ { id:'d29-t1', icon:'🧠', color:'bg-purple-50', desc:'Simulación: Haz un examen modelo de lectura (Lesen).', time:'30 min' }, { id:'d29-t2', icon:'🎧', color:'bg-pink-50', desc:'Simulación: Haz un examen modelo auditivo (Hören).', time:'30 min' }, { id:'d29-t3', icon:'🗣️', color:'bg-orange-50', desc:'Simulación: Practica la sección oral (Sprechen).', time:'30 min' } ] },
    { day: 30, word: 'das Zertifikat', wordTrans: 'el certificado', plural: 'die Zertifikate', title: '¡Felicidades! Logro A1', journalPrompt: 'Escribe tu reflexión del mes y tus metas futuras.', exampleSentence: 'Das Zertifikat ist wichtig.', exampleTranslation: 'El certificado es importante.', learningGoals: ["Reflexionar sobre el aprendizaje.", "Establecer metas para el Nivel A2."], lessonContent: `<h3>¡Lo lograste!</h3><p>El primer mes es el más difícil. Tómate el tiempo de celebrar tu logro y planear tu próximo paso.</p>`, tasks: [ { id:'d30-t1', icon:'🧠', color:'bg-purple-50', desc:'Revisa todas las tareas pendientes.', time:'30 min' }, { id:'d30-t2', icon:'✍️', color:'bg-yellow-50', desc:'Escribe la reflexión del mes en el diario.', time:'30 min' }, { id:'d30-t3', icon:'🗣️', color:'bg-orange-50', desc:'Di en voz alta 10 frases que no sabías hace un mes.', time:'30 min' } ] }
];
